[tool.poetry]
name = "nonebot2-store-test"
version = "0.1.0"
description = ""
authors = ["Lancercmd <lancercmd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
